### ISSUE TITLE
downloadable model is unavailable

### ISSUE THREAD

**Issue by jurrr** [wietsedv/bertje#11]
Currently, the BERTje model seems to be unavailable for download (https://bertje.s3.eu-central-1.amazonaws.com/ ).

On each attempt, it returns the message: 

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>CB0B32AE86ECEDB8</RequestId>
<HostId>4d9xaP3L2LMiU++7QtKIS+T7dOUAfvy+UJsdvCFy5iOfuZ40TWEEs1SEVO4azEPY9S4tDqgCeDM=</HostId>
</Error>

**Comment by wietsedv** [comment]
Thanks for noticing and reporting. I have changed the download links to the files served by Hugging Face. In any case, the recommended download method is loading `wietsedv/bert-base-dutch-cased` directly with the Transformers library as described in the [model hub](https://huggingface.co/wietsedv/bert-base-dutch-cased).

**Comment by jurrr** [comment]
Ok, thanks for your swift action and response, Wietse!
