### ISSUE TITLE
Example with newest transformers version

### ISSUE THREAD

**Issue by arnov** [wietsedv/bertje#12]
I am not too familiar with the intricacies of Transformers, but it seems the example in the README is outdated. 

I did manage to load the model using this:

```
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("wietsedv/bert-base-dutch-cased")
model = TFAutoModel.from_pretrained("wietsedv/bert-base-dutch-cased")
```

Where I believe the TFAutoModel, is specific to the Tensorflow backend.

**Comment by wietsedv** [comment]
I wouldn't say that the readme is outdated because `BertModel` is still a regularly supported method. However, this only works if you have installed PyTorch. I updated the readme.

**Comment by arnov** [comment]
I do see the import now doesn't match the code in the README, is that correct?

**Comment by wietsedv** [comment]
That was correct. Fixed it.
