### ISSUE TITLE
prepare-ud.py

### ISSUE THREAD

**Issue by jwijffels** [wietsedv/bertje#18]
I'm looking into this model in order to finetune a NER task on 18th-19th century Dutch texts. While I was preparing my data (I'm on Windows for data preparation and finetuning will happen on Google Colab) and looking at the structure you require the data to be as input to your finetuning script, I ran the prepare-ud script. 
That gave me the following error on Windows, I had to spin up an Ubuntu machine where the code did work. 
Just putting this information here so you are aware of the encoding issue.

```
$ python finetuning/prepare/prepare-ud.py -i "C:\Users\Jan\Dropbox\Work\RForgeBNOSAC\OpenSource\UD_Dutch-LassySmall" -o "data"
C:\Users\Jan\Dropbox\Work\RForgeBNOSAC\OpenSource\UD_Dutch-LassySmall
data
 > Preparing NER data
Traceback (most recent call last):
  File "finetuning/prepare/prepare-ud.py", line 104, in <module>
    main()
  File "finetuning/prepare/prepare-ud.py", line 100, in main
    save_data(prepare_ud(args.in_path), args.out_path)
  File "finetuning/prepare/prepare-ud.py", line 36, in prepare_ud
    train = read_conllu(train_path)
  File "finetuning/prepare/prepare-ud.py", line 9, in read_conllu
    for line in f:
  File "C:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1287: character maps to <undefined>
```

**Comment by wietsedv** [comment]
Thanks for letting me know. I do not use Windows and the code is mainly here for reference and not literal usage, so I do not really intend to fix it.

But if the fix is obvious, I can fix it. What python version are you using?

**Comment by jwijffels** [comment]
I ran this on Windows with the following. It's really not crucial. I just wanted to understand the data structure of the input to the finetuning training.

```
$ python --version
Python 3.6.10 :: Anaconda, Inc.
```

**Comment by wietsedv** [comment]
Python 3.6 should work. I will close this issue, but if this is a real problem for someone else: feel free to reopen this issue.

**Comment by andreasvc** [comment]
The fix is to specify utf8 encoding everywhere, or set it as the default. Windows has a different default (cp1252) because compatibility is more important to them than unicode. Another solution is to not use windows. Install Ubuntu with WSL etc.
