### ISSUE TITLE
Training Data for BERTje

### ISSUE THREAD

**Issue by siebeniris** [wietsedv/bertje#25]
Hello, 

thank you very much for BERTje!

We would like to do some analysis regarding BERT models in different languages. Is it possible to release the data you used for pre-training the model. Especially the ones without citations:

- Books: a collection of contemporary and historical fiction novels 
- Web news: all articles of 4 Dutch news websites from January 1, 2015 to October 1, 2019 (1.6GB)

Thank you very much!

**Comment by wietsedv** [comment]
Given the nature and sources of the data, we are legally unable to share these datasets. This is unfortunate for reproducability, but there is nothing we can do about it. I hope you understand.

**Comment by siebeniris** [comment]
Okay, thanks for the quick reply :)
