### ISSUE TITLE
"bert-base-dutch-cased" not recognized on huggingface transformers

### ISSUE THREAD

**Issue by DirkWW** [wietsedv/bertje#3]
Although also described in the transformers documentation the model seems not available there. 👍 

> OSError: Model name 'bert-base-dutch-cased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'bert-base-dutch-cased' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

**Comment by wietsedv** [comment]
It should be available in version 2.4+ and later. Make sure you have updated Transformers to the latest version.

**Comment by DirkWW** [comment]
Indeed, it works now. I have been looking out to test a Dutch Bert version. Thanks!
