### ISSUE TITLE
BERTje for SRL

### ISSUE THREAD

**Issue by dafnevk** [wietsedv/bertje#5]
Thanks for sharing the BERTje model!

We want to try to use BERTje for Semantic Role Labeling, which you mention as one of the tasks in the paper. Could you share the code for fine-tuning the model, and possibly also the fine-tuned model?

**Comment by losimons** [comment]
Interested in the example code as well!

**Comment by wietsedv** [comment]
*(Sorry for the late response, I did not receive/notice Github notifications.)*

See issue #4. I will include some sample code with the models.
