### ISSUE TITLE
License for pre-trained model

### ISSUE THREAD

**Issue by MobiusLooper** [wietsedv/bertje#6]
Hi!

First off, thanks a lot for making and sharing this model.

Second, is there a license that can be applied to the pre-trained model itself?

Thanks,
Josh

**Comment by wietsedv** [comment]
*(Sorry for the late response, I did not receive/notice Github notifications.)*

I am not an expert on this, but I think you may assume the same license that applies to the Arxiv paper: https://creativecommons.org/licenses/by/4.0/

Let me know if you require anything more specific / explicit.
