### ISSUE TITLE
deploy on serverless architecture

### ISSUE THREAD

**Issue by flieks** [wietsedv/bertje#8]
Someone experience with deploying this to serverless ?
AWS lambda has size restrictions to max of 512MB temp storage which is a problem.
![image](https://user-images.githubusercontent.com/5032389/79958849-ad390980-8483-11ea-8975-6c4efa5745fb.png)
Other options ? Because BERT can be GPU resource heavy if running fulltime

**Comment by wietsedv** [comment]
I cannot really help you with this. High resource requirements are unfortunately a problem for all large pre-trained language models and I do not have experience with cost-effective deployment. 

This seems like a generic problem for AWS lambda / BERT, so I think you will get a higher chance of getting a useful response if you open an issue in the original BERT repo: https://github.com/google-research/bert/issues

**Comment by flieks** [comment]
Thanks alot. Ok i will ask there
